# Generated by Django 4.2.2 on 2023-09-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0002_alter_product_cost_per_use_alter_product_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_per_use',
        ),
    ]
