# Generated by Django 4.2.2 on 2023-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание категории'),
        ),
    ]
