# Generated by Django 4.2.2 on 2023-09-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0010_product_is_archived_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
