# Generated by Django 4.2.2 on 2023-09-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created', 'is_archived'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
